# Generated by Django 5.0.2 on 2024-02-23 18:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('galeria', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='fotografia',
            name='categoria',
            field=models.CharField(choices=[('Filmes', 'Filmes'), ('Series', 'Series'), ('Animes', 'Animes')], default='', max_length=100),
        ),
    ]
