# Generated by Django 5.0.2 on 2024-02-24 19:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('galeria', '0005_alter_fotografia_foto'),
    ]

    operations = [
        migrations.AddField(
            model_name='fotografia',
            name='video',
            field=models.URLField(default=0),
            preserve_default=False,
        ),
    ]
