# Generated by Django 5.0.2 on 2024-03-23 22:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('galeria', '0009_fotografia_link'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fotografia',
            name='link',
        ),
        migrations.AlterField(
            model_name='fotografia',
            name='foto',
            field=models.URLField(),
        ),
    ]
